### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by hhefesto** [tbenst/purescript-nix-example#1]
> git clone https://github.com/tbenst/purescript-nix-example
> cd multivac
> nix-build

I suppose the second line should be `cd purescript-nix-example`

Anyways, `nix-build` throws `error: undefined variable 'mkYarnPackage' at /home/hhefesto/src/purescript-nix-example/default.nix:6:1`

I am using NixOS 19.09

**Comment by hhefesto** [comment]
Just saw that `nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz` solves this (as noted in your README)

**Comment by tbenst** [comment]
thx for catching the typo, let me know if any other issues!
